### ISSUE TITLE
Pb d'interlignage dans les blocs de pages layout liste

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/roseprimaire-check-lists#1]
https://check-lists.roseprimaire.osuny.site/sites-web/

<img width="433" alt="Capture d’écran 2024-02-20 à 22 41 23" src="https://github.com/noesya/roseprimaire-check-lists/assets/2088968/6020d9da-2ff3-4590-9b7b-f43017bf4aa6">

La ligne avec la flèche est trop haute

**Comment by alexisben** [comment]
Fixed !
